# Generated by Django 5.2.7 on 2026-05-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAventurero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('avatar', models.CharField(choices=[('avatar1', 'Niño Camisa Roja'), ('avatar2', 'Niña Trenzas'), ('avatar3', 'Niña Cabello Corto'), ('avatar4', 'Niño Chaleco Azul')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
