# Generated by Django 5.2.7 on 2026-05-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leccion_nombre', models.CharField(max_length=100)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='core.perfilaventurero')),
            ],
        ),
    ]
